version: "3.9"

services:
  db:
    image: postgres:13-buster 
    container_name: "db"
    restart: always
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cbum
    ports:
      - 3001:5432
      - 3002:80

volumes:
  postgres_data:
